#!/bin/bash
cd /home/pehem/Bureau/leshortensias.github.io
git commit -am "Modifications" >> /home/pehem/Bureau/leshortensias.github.io/_bin/mel.log
git pull --no-edit >> /home/pehem/Bureau/leshortensias.github.io/_bin/mel.log
git push >> /home/pehem/Bureau/leshortensias.github.io/_bin/mel.log
